---
version: '3'
services:
  mail:
    build: ./
#     user: "1000:1000"
    container_name: mail
    restart: unless-stopped
    ports:
      - 993:993
      - 587:587
      - 4190:4190
    volumes:
      - ./data/getmail/:/app/getmail/
      - ./data/bogofilter/:/app/bogofilter/
      - ./getmailrc/:/app/getmailrc/
      - ./dovecot/:/etc/dovecot
      # - ./letsencrypt/config/etc/letsencrypt:/etc/letsencrypt
      - ./mails/:/srv/mail/
